services:
  appsmith:
    image: appsmith/appsmith-ce:latest
    container_name: appsmith
    ports:
      - "3005:80"
    environment:
      - APPSMITH_DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - APPSMITH_ENCRYPTION_PASSWORD=${APPSMITH_ENCRYPTION_PASSWORD}
      - APPSMITH_ENCRYPTION_SALT=${APPSMITH_ENCRYPTION_SALT}
      - APPSMITH_INSTANCE_NAME=${APPSMITH_INSTANCE_NAME:-CEITBA}
      - APPSMITH_DISABLE_TELEMETRY=${APPSMITH_DISABLE_TELEMETRY:-true}
      - APPSMITH_SIGNUP_DISABLED=${APPSMITH_SIGNUP_DISABLED:-true}
    volumes:
      - appsmith_data:/appsmith-stacks
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  appsmith_data:
