services:
  postgres:
    image: postgres:16-alpine
    container_name: ceitba-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-ceitba_db}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ceitba_password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-ceitba_db}",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  ceitba-api-base:
    image: ghcr.io/ceitba/ceitba-api:${CEITBA_API_TAG:-latest}
    platform: linux/amd64
    container_name: ceitba-api
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${API_PORT:-3000}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-ceitba_password}@postgres:5432/${POSTGRES_DB:-ceitba_db}
      - ITBA_API_TOKEN=${ITBA_API_TOKEN}
      - ITBA_API_BASE_URL=${ITBA_API_BASE_URL}
      - ITBA_API_TIMEOUT=${ITBA_API_TIMEOUT:-30000}
    expose:
      - "3000"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
