
services:
  caddy:
    extends:
      file: docker/caddy/caddy.yml
      service: caddy
    networks:
      - app-network
    environment:
      - DOMAIN=${DOMAIN}
      - CORS_ORIGIN=${DOMAIN}
      - ACME_EMAIL=${ACME_EMAIL}
      - ACME_CA_SERVER=${ACME_CA_SERVER}
      - TZ=${TZ}

  envoy:
    extends:
      file: docker/envoy/envoy-service.yml
      service: envoy
    networks:
      - app-network
    environment:
      - CORS_ORIGIN=${DOMAIN}

  postgres:
    extends:
      file: docker/api/api-base.yml
      service: postgres
    networks:
      - app-network
    container_name: ceitba-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - TZ=${TZ}

  ceitba-api:
    extends:
      file: docker/api/api-base.yml
      service: ceitba-api-base
    networks:
      - app-network
    container_name: ceitba-api
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${API_PORT}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - ITBA_API_TOKEN=${ITBA_API_TOKEN}
      - ITBA_API_BASE_URL=${ITBA_API_BASE_URL}
      - ITBA_API_TIMEOUT=${ITBA_API_TIMEOUT}
      - CEITBA_API_URL=${CEITBA_API_URL}
      - TZ=${TZ}

  ceitba-scheduler:
    extends:
      file: docker/spa/scheduler.yml
      service: ceitba-scheduler
    networks:
      - app-network
    container_name: ceitba-scheduler
    environment:
      - NODE_ENV=${NODE_ENV}
      - TZ=${TZ}

  # appsmith:
  #   extends:
  #     file: docker/appsmith/appsmith.yml
  #     service: appsmith
  #   networks:
  #     - app-network
  #   container_name: appsmith
  #   depends_on:
  #     - postgres

volumes:
  caddy-certs:
    driver: local
  caddy-config:
    driver: local
  caddy-logs:
    driver: local
  appsmith_data:
  postgres_data:
    driver: local

networks:
  app-network:
    external: true
