services:
  ceitba-scheduler:
    image: ghcr.io/ceitba/scheduler:${CEITBA_SCHEDULER_TAG:-latest}
    platform: linux/amd64
    container_name: ceitba-scheduler
    environment:
      NEXT_PUBLIC_CEITBA_API_URL: ${NEXT_PUBLIC_CEITBA_API_URL}
    expose:
      - "3000"
    restart: unless-stopped
