services:
  ceitba-scheduler:
    image: ghcr.io/ceitba/scheduler:${CEITBA_SCHEDULER_TAG:-latest}
    platform: linux/amd64
    container_name: ceitba-scheduler
    environment:
      CEITBA_API_URL: ${CEITBA_API_URL:-https://localhost}
    expose:
      - "3000"
    restart: unless-stopped
